### ISSUE TITLE
Documentation issue with `proxy` config for ES output

### ISSUE THREAD

**Issue by DavidWittman** [elastic/logstash-docs#128]
The list element is being displayed incorrectly for the config description of `proxy` in the Elasticsearch output plugin. In addition, the documentation states that the value type is `string`, when it can be either a `string` or a `hash`.

From: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html

![image](https://cloud.githubusercontent.com/assets/714287/10289092/505b9e2e-6b62-11e5-88a7-25c9355bcff5.png)

``` asciidoc
[[plugins-outputs-elasticsearch-proxy]]
===== `proxy` 

  <li> Value type is <<string,string>>
  * There is no default value for this setting.
```

Should be

``` asciidoc
[[plugins-outputs-elasticsearch-proxy]]
===== `proxy` 

  * Value type is <<string,string>> or <<hash,hash>>
  * There is no default value for this setting.
```

I'd open a PR, but this project's README seems to indicate that I should not do that. How else can I submit these changes?

**Comment by untergeek** [comment]
@DavidWittman if you go back to the linked html page, there should be some _edit_ links to the right of the text blocks.  If you click the appropriate one, it will take you to the correct github page, and open the document for editing.

**Comment by untergeek** [comment]
And I mean the link you provided: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html

**Comment by DavidWittman** [comment]
Hey @untergeek... Thanks for the help. However, I'm unable to find how the value type is determined from the source there:

``` ruby
  # Set the address of a forward HTTP proxy. 
  # Can be either a string, such as `http://localhost:123` or a hash in the form
  # of `{host: 'proxy.org' port: 80 scheme: 'http'}`.
  # Note, this is NOT a SOCKS proxy, but a plain HTTP proxy
  config :proxy
```

Same goes for the incorrect `<li>` tag.

**Comment by DavidWittman** [comment]
Looks like using

``` ruby
config :proxy, :validate => %w(string, hash)
```

may work here. I suppose this may be causing the `<li>` tag anyway, so I'll keep digging.

**Comment by untergeek** [comment]
I'm guessing that the `<li>` may be an issue with our documentation generator.  

The documentation generator parses the text above `config :proxy` and puts the "Value type" text in for you.  

Adding the `:validate => ` may fool the generator, but I don't know if we want to add the `%w(string, hash)`, as I don't know if the generator knows what to do with it.  It already presumes string, erroneously.

**Comment by dedemorton** [comment]
Closing this issue because the logstash doc generator has been updated and the formatting issue no longer exists. If additional doc changes are required, please open an issue in the [main logstash repo](https://github.com/elastic/logstash). The logstash-docs repo is meant to be read-only; we don't track issues here.
