### ISSUE TITLE
Kafka input/output installation instructions for 0.8 vs 0.9

### ISSUE THREAD

**Issue by sarwarbhuiyan** [elastic/logstash-docs#256]
It might be useful to put in the input installation instructions for Kafka input and output based on which broker the user is using. 

"bin/logstash-plugin install --version 3.0.3 logstash-input-kafka" vs "bin/logstash-plugin install --version 2.0.9" logstash-input-kafka

**Comment by dedemorton** [comment]
logstash-docs is a read-only repo. We don't want people opening issues against this repo, so I've created  https://github.com/elastic/logstash/issues/6770 to replace this issue.
