### ISSUE TITLE
Documentation on how to generate the docs from source is not included.

### ISSUE THREAD

**Issue by ava-dylang** [elastic/logstash-docs#71]
Also it looks like this is not a source code repository at all, should put your doc generator in here and make releases with github's tag+releases feature. Maybe, if you want. :hugs:

**Comment by untergeek** [comment]
As is mentioned in the [README](https://github.com/elastic/logstash-docs/blob/master/README.md), this repository is really just for internal use.  We push rendered docs here, and they are then picked up by our automatic documentation generator.

Edits to plugin documentation should be added inline to the individual plugin as a pull request.

Edits to core Logstash documentation should also be a pull request, at https://github.com/elastic/logstash, in the docs/asciidoc folder of that repository.
